name: cd-branch-mockup

on:
  push:
    branches:
      - mockup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html/mockup_joglo/joglo
            git pull origin mockup
            export PATH="$PATH:/root/.nvm/versions/node/v20.13.1/bin"
            echo $PATH
            npm install
            npm run build
