name: cd-branch-layout

on:
  push:
    branches:
      - layout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html/joglo
            git pull origin layout
            source ~/.bashrc
            /root/.nvm/versions/node/v20.13.1/bin/npm install
            /root/.nvm/versions/node/v20.13.1/bin/npm run build
            chmod +x automation_build_path.sh
            ./automation_build_path.sh
